In [199]:
# 1. Write a Python Program to Add Two Matrices?

def matrix(r,c,l):
    import numpy as np
    try:
        """ r -- no. of rows
            c -- no. of columns
            l1 -- list of elements to be in the matrix 
               -- len(l1) = r*c """
        matrix = np.array(l).reshape(r,c)
        return (matrix)
    except Exception as e:
        print(e)

l1=[10,20,30,40,50,60,70,80]
l2=[100,200,300,400,500,600,700,800]
try:
    a = matrix(2,4,l1)
    b = matrix(2,4,l2)
    print("The given matrix:")
    print(a)
    print(b)
    print("Output:")
    for i in range(len(a)):
        x =[]
        for j in range(len(a[i])):
            r = a[i][j]+b[i][j]
            x.append(r)
        print(x)
except Exception as e:
        print(e)

The given matrix:
[[10 20 30 40]
 [50 60 70 80]]
[[100 200 300 400]
 [500 600 700 800]]
Output:
[110, 220, 330, 440]
[550, 660, 770, 880]


In [198]:
# 2. Write a Python Program to Multiply Two Matrices?

l = [1,3,5,7,11,13,17,19,23]
l1= [2,4,6,8,10,12,14,16,18]
try:
    a = matrix(3,3,l)
    b = matrix(3,3,l1)
    print("The given matrix:")
    print(a)
    print(b)
    print("Output:")
    for i in range(len(a)):
        x =[]
        for j in range(len(a[i])):
            r = a[i][j]*b[i][j]
            x.append(r)
        print(x)
except Exception as e:
        print(e)

The given matrix:
[[ 1  3  5]
 [ 7 11 13]
 [17 19 23]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Output:
[2, 12, 30]
[56, 110, 156]
[238, 304, 414]


In [196]:
# 3. Write a Python Program to Transpose a Matrix?

l = [10,20,30,40,50,60,70,80,90,100,110,120]

a = matrix(3,4,l)
b = a.shape
r = b[1]
c = b[0]
x =[]
print("The given matrix:")
print(a)
print("Output:")
try:
    for i in range(len(a)):
        for j in range(len(a[i])):
            x.append(a[i][j])

    transpose = matrix(r,c,x)
    print(transpose)
except Exception as e:
        print(e)

The given matrix:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Output:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [237]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?

try:
    a = str(input("Enter the string:"))
    a = a.lower()
    s = a.split()
    s.sort()
    print(s,end=" ")
except Exception as e:
        print(e)

Enter the string:I looked for Mary and Samantha at the bus station
['and', 'at', 'bus', 'for', 'i', 'looked', 'mary', 'samantha', 'station', 'the'] 

In [251]:
# 5. Write a Python Program to Remove Punctuation From a String?

p = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

a = str(input("Enter the string: "))

for i in a:
    if i not in p:
        print(i,end="")
print(" ")

Enter the string: In each town-London, Paris and Rome-we stayed in youth hostels.
In each townLondon Paris and Romewe stayed in youth hostels 
